# Generated by Django 5.1.6 on 2025-04-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="communicationthread",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In Progress"),
                    ("closed", "Closed"),
                    ("awiating_vendor_reply", "Awaiting Vendor Reply"),
                    ("awiating_admin_reply", "Awaiting Admin Reply"),
                    ("awiating_customer_reply", "Awaiting Customer Reply"),
                ],
                default="open",
                max_length=30,
            ),
        ),
    ]
