# Generated by Django 5.1.6 on 2025-04-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0002_communicationthread_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="communication_files/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
