# Generated by Django 5.1.6 on 2025-04-12 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "__first__"),
        ("users", "0006_customer_first_name_customer_last_name"),
        ("vendor", "0007_vendor_balance_vendor_pending_balance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CONFIRMED", "Order Confirmed"),
                            ("PREPARING", "Preparing"),
                            ("OUT_FOR_DELIVERY", "Partially Out for Delivery"),
                            ("DELIVERED", "Partially Delivered"),
                            ("FULLY_DELIVERED", "Delivered"),
                            ("RETURN_REQUESTED", "Return Requested"),
                            ("RETURNED_REFUNDED", "Returned & Refunded"),
                            ("CANCELED_BY_VENDOR", "Canceled by Vendor"),
                            ("CANCELED_BY_CUSTOMER", "Canceled by Customer"),
                        ],
                        default="CONFIRMED",
                        max_length=255,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="users.customer",
                    ),
                ),
                (
                    "vendors",
                    models.ManyToManyField(related_name="orders", to="vendor.vendor"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_paid", models.BooleanField(default=False)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CONFIRMED", "Item Confirmed"),
                            ("PREPARING", "Preparing"),
                            ("OUT_FOR_DELIVERY", "Out for Delivery"),
                            ("DELIVERED", "Delivered"),
                            ("RETURN_REQUESTED", "Return Requested"),
                            ("RETURNED_REFUNDED", "Returned & Refunded"),
                            ("CANCELED_BY_VENDOR", "Canceled by Vendor"),
                            ("CANCELED_BY_CUSTOMER", "Canceled by Customer"),
                        ],
                        default="CONFIRMED",
                        max_length=255,
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="order.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="product.product",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="vendor.vendor",
                    ),
                ),
            ],
        ),
    ]
