# Generated by Django 5.1.6 on 2025-03-06 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_first_name_remove_user_last_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendor",
            name="user",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="location_of_residency",
        ),
        migrations.DeleteModel(
            name="AdminProfile",
        ),
        migrations.DeleteModel(
            name="Vendor",
        ),
    ]
