# Generated by Django 5.1.6 on 2025-03-08 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_vendor_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterModelTable(
            name="customer",
            table="customers",
        ),
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
    ]
