# Generated by Django 5.1.6 on 2025-04-13 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformFinance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "pending_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "platform_finance",
            },
        ),
        migrations.CreateModel(
            name="PlatformSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="Area13 Marketplace", max_length=255),
                ),
                ("site_description", models.TextField(blank=True, null=True)),
                (
                    "support_email",
                    models.EmailField(default="support@example.com", max_length=254),
                ),
                ("default_currency", models.CharField(default="USD", max_length=10)),
                ("commission_rate", models.FloatField(default=10.0)),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("platform_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "platform_settings",
            },
        ),
        migrations.CreateModel(
            name="PlatformStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_sales", models.PositiveIntegerField(default=0)),
                ("total_customers", models.PositiveIntegerField(default=0)),
                ("active_total_products", models.PositiveIntegerField(default=0)),
                ("active_vendors_count", models.PositiveIntegerField(default=0)),
                ("new_customers_this_month", models.PositiveIntegerField(default=0)),
                (
                    "monthly_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("last_week_sales", models.PositiveIntegerField(default=0)),
                ("this_week_sales", models.PositiveIntegerField(default=0)),
                (
                    "last_week_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "this_week_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Admin",
        ),
    ]
