# Generated by Django 5.1.6 on 2025-04-25 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "admin_dashboard",
            "0002_platformfinance_platformsettings_platformstats_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="platformstats",
            old_name="active_total_products",
            new_name="this_month_new_customers",
        ),
        migrations.RenameField(
            model_name="platformstats",
            old_name="monthly_revenue",
            new_name="this_month_revenue",
        ),
        migrations.RemoveField(
            model_name="platformstats",
            name="active_vendors_count",
        ),
        migrations.RemoveField(
            model_name="platformstats",
            name="new_customers_this_month",
        ),
        migrations.RemoveField(
            model_name="platformstats",
            name="total_customers",
        ),
        migrations.RemoveField(
            model_name="platformstats",
            name="total_sales",
        ),
    ]
