# Generated by Django 5.1.6 on 2025-04-22 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_product_application_type_product_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price_currency",
            field=models.CharField(default="SAR", max_length=10),
        ),
    ]
