# Generated by Django 5.1.6 on 2025-04-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_product_price_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price_currency",
            field=models.CharField(blank=True, default="SAR", max_length=10, null=True),
        ),
    ]
