# Generated by Django 5.1.6 on 2025-04-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_alter_product_price_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="active",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the product is active and visible.",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="deactivated_by_admin",
            field=models.BooleanField(
                default=False,
                help_text="If True, only the admin can reactivate this product.",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Approval"),
                    ("REJECTED", "Rejected"),
                    ("ACTIVE", "Active"),
                    ("DEACTIVATED_VENDOR", "Deactivated"),
                    ("DEACTIVATED_ADMIN", "Deactivated by Admin"),
                ],
                default="PENDING",
                help_text="Current status of the product.",
                max_length=20,
            ),
        ),
    ]
