# Generated by Django 5.1.6 on 2025-04-25 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_payment_id",
                    models.CharField(
                        help_text="Unique payment ID provided by Stripe",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount attempted for the payment",
                        max_digits=8,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        help_text="Currency used for the payment", max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        help_text="Status of the payment as returned by Stripe",
                        max_length=50,
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        help_text="Raw response data from Stripe for debugging purposes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin_transaction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin transaction associated with this payment reference",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_references",
                        to="payment.admintransaction",
                    ),
                ),
                (
                    "vendor_transaction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vendor transaction associated with this payment reference",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_references",
                        to="payment.vendortransaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount requested for the payout",
                        max_digits=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(help_text="Currency of the payout", max_length=10),
                ),
                (
                    "transaction_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("MISSING_ITEMS", "Missing Items"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        help_text="Transaction status of the payout request",
                        max_length=20,
                    ),
                ),
                (
                    "payout_status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("REVIEW", "Reviewed by Admin"),
                            ("SENT_TO_BANK", "Sent to Bank"),
                            ("MARK_AS_COMPLETE", "Mark as Complete"),
                        ],
                        default="REQUESTED",
                        help_text="Current phase of the payout process",
                        max_length=20,
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the payout was requested",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the payout was processed",
                        null=True,
                    ),
                ),
                (
                    "transaction_reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference ID for the payout transaction",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Vendor requesting the payout",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
